apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-bitnami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: '16.7.27'
    helm:
      releaseName: postgres-demo
      values: |
        auth:
          username: admin
          password: admin123
          database: mydb
        primary:
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
