name: CD - Deploy (KinD)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag de la imagen Docker a desplegar (p.ej. latest o sha)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging   # coincide con tu Environment creado

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start KinD cluster
        uses: helm/kind-action@v1

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: (Opcional) Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Deploy with Helm to KinD
        env:
          IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          echo "Deploying image: ${IMAGE_REPO}/k8s-app:${IMAGE_TAG}"
          helm upgrade --install k8s-app charts/app \
            --set image.repository=${IMAGE_REPO}/k8s-app \
            --set image.tag=${IMAGE_TAG}
          kubectl get pods,svc -o wide

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/k8s-app --timeout=180s

      - name: Show final status
        run: |
          kubectl get pods -o wide
          kubectl get svc -o wide
